# Generated by Django 4.2.3 on 2023-08-11 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_wallet_user'),
        ('coupon', '0002_coupon_max_rate_coupon_min_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couponuser', to='coupon.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.users')),
            ],
        ),
    ]
