# Generated by Django 4.2.3 on 2023-08-11 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_wallet_user'),
        ('coupon', '0003_couponused'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CouponUsed',
            new_name='CouponUser',
        ),
    ]
