# Generated by Django 4.2.3 on 2023-07-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='discription',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
