# Generated by Django 4.2.3 on 2023-07-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('offer', '0003_offer_category_eligible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='category_eligible',
        ),
        migrations.AddField(
            model_name='offer',
            name='category_eligible',
            field=models.ManyToManyField(default=None, to='category.category'),
        ),
    ]
