# Generated by Django 4.2.3 on 2023-07-29 17:14

from django.db import migrations, models
import offer.models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0006_remove_offer_category_eligible_offercategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_num',
            field=models.CharField(default=offer.models.Offer.generate_order_id, max_length=10),
        ),
    ]
