# Generated by Django 4.2.3 on 2023-07-29 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0007_offer_offer_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offercategory',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoryEligible', to='offer.offer'),
        ),
    ]
