# Generated by Django 4.2.3 on 2023-07-14 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_cart_cartitems_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='address',
            name='address_line_1',
            field=models.CharField(default='NULL', max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='NULL', max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default='NULL', max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='full_name',
            field=models.CharField(default='NULL', max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='postal_code',
            field=models.CharField(default='NULL', max_length=10),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(default='NULL', max_length=255),
        ),
        migrations.AddField(
            model_name='cart',
            name='Address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.users'),
        ),
    ]
