# Generated by Django 4.2.3 on 2023-08-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cart_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='varient',
            field=models.CharField(default='6-10yr', max_length=20),
        ),
    ]
