# Generated by Django 4.2.3 on 2023-08-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitems_varient'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='last_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
