# Generated by Django 4.2.3 on 2023-08-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_last_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_coupon',
            field=models.BooleanField(default=False),
        ),
    ]
