# Generated by Django 4.2.3 on 2023-08-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_remove_cart_is_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_coupon',
            field=models.BooleanField(default=False),
        ),
    ]
