# Generated by Django 4.2.3 on 2023-07-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderdetail_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='order_status',
            field=models.CharField(choices=[('order_confirmed', 'Order Confirmed'), ('order_cancelled', 'Order Cancelled'), ('order_pending', 'Order Pending'), ('order_deliverd', 'Order Delivered'), ('order_shipped', 'Order Shipped'), ('order_outofdelivery', 'Order Out of Delivery'), ('order_returned', 'Order Returned'), ('order_cancelled', 'Order Cancelled')], default='Order Confirmed', max_length=50),
        ),
    ]
