# Generated by Django 4.2.3 on 2023-07-19 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderdetail_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='user',
        ),
    ]
