# Generated by Django 4.2.3 on 2023-07-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_order_order_status_orderdetail_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cash_on_delivery', 'CASH ON DELIVERY'), ('online_payment', 'Online Payment')], default='Cash on delivery', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order_status',
            field=models.CharField(choices=[('order_confirmed', 'Order Confirmed'), ('order_cancelled', 'Order Cancelled'), ('order_pending', 'Order Pending'), ('order_deliverd', 'Order Delivered'), ('order_shipped', 'Order Shipped'), ('order_outofdelivery', 'Order Out of Delivery'), ('order_returned', 'Order Returned')], default='Order Confirmed', max_length=50),
        ),
    ]
