# Generated by Django 4.2.3 on 2023-07-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_order_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_deliverd',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
