# Generated by Django 4.2.3 on 2023-07-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_order_date_deliverd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_deliverd',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='date_deliverd',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
