# Generated by Django 4.2.3 on 2023-07-25 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_remove_order_date_deliverd_orderdetail_date_deliverd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='date_deliverd',
            new_name='date_delivered',
        ),
    ]
