# Generated by Django 4.2.3 on 2023-07-27 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_rename_date_deliverd_orderdetail_date_delivered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Returned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('details', models.TextField(blank=True, default=None, null=True)),
                ('date_submitted', models.DateTimeField(auto_now=True)),
                ('date_returned', models.DateTimeField(blank=True, default=None, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned', to='order.orderdetail')),
            ],
        ),
    ]
