# Generated by Django 4.2.3 on 2023-07-27 09:10

from django.db import migrations, models
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='returned',
            name='return_num',
            field=models.CharField(default=order.models.Returned.generate_return_id, max_length=20),
        ),
    ]
