# Generated by Django 4.2.3 on 2023-07-31 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_alter_order_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='products_price',
            field=models.FloatField(default=0),
        ),
    ]
