# Generated by Django 4.2.3 on 2023-08-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_alter_orderdetail_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='products_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
