# Generated by Django 4.2.3 on 2023-08-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_orderdetail_payed_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='payed_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='payed_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
