# Generated by Django 4.2.3 on 2023-07-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='stocks',
            field=models.IntegerField(default=0),
        ),
    ]
