# Generated by Django 4.2.3 on 2023-07-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discription',
            field=models.TextField(default='NONE'),
        ),
    ]
