# Generated by Django 4.2.3 on 2023-07-30 06:20

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_products_original_price_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='original_price',
            field=models.FloatField(default=products.models.Products.make_price),
        ),
    ]
