# Generated by Django 4.2.3 on 2023-08-02 15:24

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_products_original_price_alter_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=products.models.Products.make_price, max_digits=20),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
