# Generated by Django 4.2.3 on 2023-08-03 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_varient_varient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varient',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varient', to='products.products'),
        ),
    ]
