# Generated by Django 4.2.3 on 2023-08-04 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_products_varient_delete_varient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='varient',
        ),
        migrations.CreateModel(
            name='Varient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varient', models.CharField(choices=[('1-3yr', 'XS'), ('3-5yr', 'XM'), ('6-8yr', 'MS'), ('9-12yr', 'ML'), ('12-15yr', 'L')], default='6-8yr', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
    ]
