# Generated by Django 4.2.3 on 2023-08-04 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_products_varient_varient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varient',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varient', to='products.products'),
        ),
    ]
